name: ac_recog_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  bloc: ^8.1.2
  copy_with_extension: ^5.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors.git
      ref: master
  objectbox: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  tflite_flutter:
    git:
      url: https://github.com/qren0neu/flutter-tflite-flex.git
      ref: main
  timeago: ^3.5.0
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  objectbox_generator: ^2.1.0

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/images/actrack_icon.png"
  image_path: "assets/images/actrack_icon.png"
  android: true
  ios: true
  background_color_ios: "#f95418"
  adaptive_icon_background: "#f95418"

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
